### ISSUE TITLE
ERROR: Unbound variable: argmin

### ISSUE THREAD

**Issue by gmlang** [panicz/pamphlet#10]
This error appears after running `(use-modules (ice-9 nice-9) (srfi srfi-1) (pamphlet))`
No errors if I run `(use-modules (ice-9 nice-9) (srfi srfi-1))`

**Comment by panicz** [comment]
Which version of Guile are you using?

**Comment by gmlang** [comment]
GNU Emacs 25.2.1
guile (GNU Guile) 2.2.2

**Comment by panicz** [comment]
I'm trying to build guile-2.2 right now to see what could be going on.
Do any other error messages appear when trying to load the (pamphlet) module?

**Comment by panicz** [comment]
I suspect that something about the compilation strategy could have changed between guile-2.0 and guile-2.2. You can try the following trick: replace the definition of the `e.g.` special form (lines 71-86 in pamphlet.scm) with the following one:

`(define-syntax (e.g. . _) (begin))`

and then see how it works

**Comment by gmlang** [comment]
It gives me a syntax error. 
` source expression failed to match any pattern in form (define-syntax (e.g. . _) (syntax-rules (begin) ((_ example) (or example (error (quote example)))) ((_ example ===> value) (let ((result example)) (if (equal? result (quote value)) result (error (quote (example ===> value)))))) ((_ example ===> values ...) (call-with-values (lambda () example) (lambda results (equal? results (quote (values ...)))))) ((_ example ~~~> value) example)))`

I only changed line 71. Any other places I need to change? I'm new to scheme.

**Comment by panicz** [comment]
I made a new branch with that change, called guile-2.2-issues.
The edited file is here: https://github.com/panicz/pamphlet/blob/guile-2.2-issues/libraries/pamphlet.scm
Let me know if that resolves the issue

**Comment by gmlang** [comment]
Yes, working now. Thanks!
