### ISSUE TITLE
without-default not explained

### ISSUE THREAD

**Issue by pfusik** [panicz/pamphlet#18]
Chapter 5 contains:

    (without-default ((universe '(()()))
                      (unknown? (lambda (x) (eq? x '?))))

but doesn't explain `without-default`. It is therefore unclear to the reader. WTFM. ;)

**Comment by panicz** [comment]
This is a 'bug' actually: the code should have used the `with-default' form, which -- as I recall -- has been explained. (The code accompanying the book does define the 'without-default' form, but in a way that is incompatible with the above usage). Thanks for vigilance!
