### ISSUE TITLE
[trivial] on expression-based programming

### ISSUE THREAD

**Issue by drcz** [panicz/pamphlet#3]
...but might make a smashing footnote:

1) some people call it "applicative programming" (https://en.wikipedia.org/wiki/Applicative_programming_language)
-- I believe I've seen some 1960s paper using the term to describe lisp/iswim-like languages (or maybe I haven't?).

2) the term "functional programming" was used by Backus in his Palme d'Or winning "Can Programming Be Liberated from the von Neumann Style?" for [what seems to be nowadays called] tacit programming ("variable-free", "point-free", or even "pointless").

**Comment by panicz** [comment]
May I suggest that you create a separate branch (or branches) where you
make whichever changes you like, and then create pull requests, or perhaps
I could merge those branches to main - it would make it much easier to
maintain your issues.

While I find these remarks very interesting, I think that they go far
beyond the main topic of the book. Perhaps it would make sense to rephrase
that statement and give a citation/reference to Backus' paper. OTOH the
wikipedia entry regarding applicative programming is rather scarce. If the
term was equivalent to what is meant by 'expression based programming'
(which is explained in a footnote in the second chapter AFAIR), then it
would be best to avoid introducing new terms and go with 'applicative
programming'. On the other hand, I don't think that using the term
'applicative programming' explains much, as it focuses on the notion of
application, which is itself a rather technical term.

**Comment by drcz** [comment]
good, a branch. although I hoped you still don't use computer on Sundays and was about to push my changes to main. damn!

definitely I only though about footnote (or just informing you), as I find "expression based programming" an excellent name.
closing.

**Comment by panicz** [comment]
I didn't.  I replied from my phone :)

**Comment by drcz** [comment]
https://i.ytimg.com/vi/H-fAW-HD96A/hqdefault.jpg
