### ISSUE TITLE
[suggestions] prime numbers and divisors

### ISSUE THREAD

**Issue by drcz** [panicz/pamphlet#4]
as was mentioned in the text, **prime-numbers** and **divisors** have very similar definitions; but the symmetry breaks in their applications: we have **(divisors number 1)** but **(prime-numbers 7 0)**.

i suggest restricting all the definitions to positive integers [maybe even state that explicitly] to have **(prime numbers 7 1)** [otherwise the definition of divisors would get more complicated].

i'm tempted to suggest **(define (all-divisors number) (divisors number 1))** and use it in definition of **prime?** -- which nb i really like, and find it funny that it's not trivially equivalent to
**(= (length (all-divisors number)) 2)**.

**Comment by panicz** [comment]
I like the suggestion regarding the restriction to positive numbers. The
idea of adding 'all-divisors' I find a bit controversial. While it makes
the text of the code easier to read, it makes the text slightly longer, and
another definition is another thing for a reader to remember (which means
some intellectual effort on reader's side). Also, there's a linguistic
structure that isn't reflected in the semantics - one could wish that 'all'
is a special operator, and 'all divisors of 5' be translated as (all
(divides? 5)) -- which can't be easily expressed in the semantics of Scheme.

**Comment by drcz** [comment]
I believe your parents were controversial when they conceived you, sir.
first suggestion pushed to "my" branch, for the second I totally buy your arguments.

_what you wrote about this "all" construct is quite enlightening_
