### ISSUE TITLE
[grammar] is a few concepts?

### ISSUE THREAD

**Issue by drcz** [panicz/pamphlet#5]
"In Scheme, there is a few distinct concepts of equality" -- perhaps "there's a few" or "there are a few" as "concepts" seem plural... or not? (page 15).

**Comment by panicz** [comment]
you're right, my mistake. I owe you ;)

**Comment by drcz** [comment]
i thought i wrote there a request for native speaker to decide. my english much not happy. what a useless issue! hope we gain contribution counts for that, and some day will win something fancy.
