### ISSUE TITLE
[suggestion] "next" in def. of "lookup"?

### ISSUE THREAD

**Issue by drcz** [panicz/pamphlet#7]
pages 22 and 23, in definition(s) of **lookup**:
**(cdr mapping)** is called **next** -- perhaps a more adequate name would be "rest" [maybe a bit unfortunate] or [better] "remaining"? i think "next" fits better to **(cadr mapping)**... or maybe it doesn't?

**Comment by panicz** [comment]
I'm not sure. If you read 'next' as singular form then you are surely
right, but if you think of it as plural, then the intention gets clearer.
But I do agree that your suggestion avoids that ambiguity, and is therefore
better, so feel free to fix that ;)

**Comment by drcz** [comment]
boom, pushed to derczykowy
