### ISSUE TITLE
Slight issue in Pamphlet front screen

### ISSUE THREAD

**Issue by kreely** [panicz/pamphlet#9]
G'day Panicz,
The web rendered text of your pamphlet web page (2nd paragraph) says :
   ... since the 70, and ...
I think you mean since the 70's? You could either spell it out as seventies or if you want to stick with numerics it probably needs an escape somewhere (perhaps for the quote).

Great pamphlet by the way. Your intro gels with my experience of software all over the place. I use Common Lisp a lot, but I can get around in Scheme/Guile and being lisp-like it's so much nicer than nearly all of the other environments I can think of.

Thanks for writing it. All the best.

Regards,
David

**Comment by panicz** [comment]
Fixed, thanks! :)
